#!/usr/bin/expect
###########################################################################################
## Copyright 2003, 2015 IBM Corp                                                          ##
##                                                                                        ##
## Redistribution and use in source and binary forms, with or without modification,       ##
## are permitted provided that the following conditions are met:                          ##
##	1.Redistributions of source code must retain the above copyright notice,          ##
##        this list of conditions and the following disclaimer.                           ##
##	2.Redistributions in binary form must reproduce the above copyright notice, this  ##
##        list of conditions and the following disclaimer in the documentation and/or     ##
##        other materials provided with the distribution.                                 ##
##                                                                                        ##
## THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS AND ANY EXPRESS       ##
## OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF        ##
## MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ##
## THE AUTHOR OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,    ##
## EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF     ##
## SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) ##
## HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,  ##
## OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS  ##
## SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.                           ##
############################################################################################
#create a screen by giving a socket name
spawn /bin/sh
 spawn  screen -S testscreen
 expect "\# "
#sending ctrl + a + d (#)
 send "#\r"
 expect "\# "
#Attach to a not detached screen
 spawn screen -x testscreen
 expect "\# "
 send "#\r"
 expect "\# "
#Reattach if possible, otherwise start a new session
 spawn screen -R testscreen
 expect "\# "
 send "#\r"
 expect "\# "
send "exit\r"
 expect "\# "


#Start screen as daemon: Screen session in detached mode
spawn screen -dmS mydaemon
expect "\# "
#After reattaching to the screen it gets exited automatically in expect script
spawn screen -S mydaemon -r

#Turn on output logging
spawn screen -L
expect "\# "
send "echo hi"
expect "hi \r"
send "exit"
expect "\# "

#Read configuration file instead of '.screenrc'
spawn screen -c config.txt
send "exit"
expect "\# "

