#
# configuration of mcf files
#
#

#
# fs allocations
#
fs-config-ms-dk: &fs-config-ms
    Qfs2:
      type: ms
      mr_as_md: True
      eq_list: [md, md, md]
    Qfs3:
      type: ms
      eq_list: [md]
    Qfs4:
      type: ms
      eq_list: [md]

fs-config-3fs-dk: &fs-config-std
    Qfs2:
      type: ma
      eq_list: [mm, mr, mr]
    Qfs3:
      type: ms
      eq_list: [md]
    Qfs4:
      type: ms
      eq_list: [md]

# standard with faster 2nd copy dk
fs-config-3fs-fast-dk: &fs-config-fast
    Qfs2:
      type: ma
      eq_list: [mm, mr, mr]
    Qfs3:
      type: ms
      eq_list: [md]
    Qfs4:
      type: ma
      eq_list: [mm, md]

# standard with faster 2nd copy dk, and 2nd 3rd copy
fs-config-4fs-dk: &fs-config-4fs
    Qfs2:
      type: ma
      eq_list: [mm, mr, mr]
    Qfs3:
      type: ms
      mr_as_md: True
      eq_list: [md]
    Qfs4:
      type: ma
      mr_as_md: True
      eq_list: [mm, md]
    Qfs5:
      type: ms
      eq_list: [md, md]
        #
# standard with lots of ms/md
fs-config-5fs-dk: &fs-config-5fs
    Qfs2:
      type: ma
      eq_list: [mm, mr, mr]
    Qfs3:
      type: ms
      mr_as_md: True
      eq_list: [md]
    Qfs4:
      type: ms
      mr_as_md: True
      eq_list: [md]
    Qfs5:
      type: ms
      eq_list: [md]
    Qfs6:
      type: ms
      eq_list: [md]

# 2 mm, fast dk both
fs-config-fast-dk2: &fs-config-fast-dk2
    Qfs2:
      type: ma
      eq_list: [mm, mm, mr, mr, mr, mr]
    Qfs3:
      type: ms
      eq_list: [md, md, md]
    Qfs4:
      type: ms
      eq_list: [md, md, md]

# grow
fs-config-grow: &fs-config-grow
    Qfs2:
      type: ma
      eq_list: [mm, mr, mr, mm, mr, mr]
    Qfs3:
      type: ms
      eq_list: [md]
    Qfs4:
      type: ms
      eq_list: [md]

# XXX would be nice to say 'all-mr'
fs-config-big-nodk: &fs-config-big
    Qfs2:
      type: ma
      eq_list: [mm, mr, mr, mr, mr]

fs-config-big-ms-nodk: &fs-config-big-ms
    Qfs2:
      type: ms
      mr_as_md: True
      eq_list: [md, md, md, md]

#
# fs options
#
fs-opt-share-qfs2: &fs-shared-std
    Qfs2:
      add_params: shared

#
# mcf configs
# fs layout
# fs options
# etc
#
mcf:
  normal:
    fname: mcf
    qfs_config: *fs-config-std

  normal_shared:
    fname: mcf_shared
    qfs_config: *fs-config-std
    qfs_options: *fs-shared-std

  3fs-fast:
    fname: mcf_3fs
    qfs_config: *fs-config-fast

  4fs:
    fname: mcf_4fs
    qfs_config: *fs-config-4fs

  5fs:
    fname: mcf_5fs
    qfs_config: *fs-config-5fs

  ms:
    fname: mcf_ms
    qfs_config: *fs-config-ms

  grow:
    fname: mcf_grow
    qfs_config: *fs-config-grow

  fast-dk2:
    fname: mcf_fast_dk2
    qfs_config: *fs-config-fast-dk2

  one_big:
    fname: mcf_one_big
    qfs_config: *fs-config-big

  one_big_shared:
    fname: mcf_one_big_shared
    qfs_config: *fs-config-big
    qfs_options: *fs-shared-std

  one_big_ms:
    fname: mcf_one_big_ms
    qfs_config: *fs-config-big-ms

  one_big_ms_shared:
    fname: mcf_one_big_ms_shared
    qfs_config: *fs-config-big-ms
    qfs_options: *fs-shared-std


