#
# configuration for the main set of disks
#

# simple VSM for smoke testing - VM on real HW
# lsblk:
# vdb                         252:16   0   32G  0 disk
# vdc                         252:32   0  128G  0 disk
# vdd                         252:48   0  128G  0 disk

# format is
# /path/to/disk:
#   partno:
#     size: 64GB


partitions:
  /dev/vdb:
    1:
      size: 16GB
    2:
      size: 16GB
  /dev/vdc:
    1:
      size: 32GB
    2:
      size: 32GB
    3:
      size: 32GB
    4:
      size: 32GB
  /dev/vdd:
    1:
      size: 64GB
    2:
      size: 64GB

#
# describe the disks/partitions in terms of VSM filesystems
# mm: meta data devices
# mr: data devices, can double as mm or mr
# md: strictly md for disk archiving or other slower access
#
vsm_disks:
    mm:
      - /dev/vdb1
      - /dev/vdb2
    mr:
      - /dev/vdc1
      - /dev/vdc2
      - /dev/vdc3
      - /dev/vdc4
    md:
      - /dev/vdd1
      - /dev/vdd2

# 
# list of qfs configurations that are valid
#
valid_qfs_configs: normal, normal_shared, ms, one_big, one_big_shared, one_big_ms, one_big_ms_shared, 4fs
