#
# configuration for the main set of disks
#

# simple VSM for smoke testin
# lsblk:
# sdb                           8:16   0    8G  0 disk
# sdc                           8:32   0   32G  0 disk
# sdd                           8:48   0   32G  0 disk

# format is
# /path/to/disk:
#   partno:
#     size: 64GB


partitions:
  /dev/sdc:
    1:
      size: 8GB
    2:
      size: 12GB
    3:
      size: 12GB
  /dev/sdd:
    1:
      size: 16GB
    2:
      size: 16GB

#
# describe the disks/partitions in terms of VSM filesystems
# mm: meta data devices
# mr: data devices, can double as mm or mr
# md: strictly md for disk archiving or other slower access
#
vsm_disks:
    mm:
      - /dev/sdb
    mr:
      - /dev/sdc1
      - /dev/sdc2
      - /dev/sdc3
    md:
      - /dev/sdd1
      - /dev/sdd2

# 
# list of qfs configurations that are valid
#
valid_qfs_configs: normal, normal_shared, ms
