perl -I../lib base._calc_date_ymwd.t 1
perl -I../lib base._config.t 1
perl -I../lib base._critical_date.t 1
perl -I../lib base._fix_year.50.t 1
perl -I../lib base._fix_year.c.t 1
perl -I../lib base._fix_year.c18.t 1
perl -I../lib base._fix_year.c1890.t 1
perl -I../lib base.calc_date_date.t 1
perl -I../lib base.calc_date_days.t 1
perl -I../lib base.calc_date_delta.t 1
perl -I../lib base.calc_date_time.t 1
perl -I../lib base.calc_time_time.t 1
perl -I../lib base.check.t 1
perl -I../lib base.cmp.t 1
perl -I../lib base.day_of_week.t 1
perl -I../lib base.day_of_year.0.t 1
perl -I../lib base.day_of_year.1.t 1
perl -I../lib base.days_in_month.t 1
perl -I../lib base.days_in_year.t 1
perl -I../lib base.days_since_1bc.t 1
perl -I../lib base.join.t 1
perl -I../lib base.leapyear.t 1
perl -I../lib base.nth_day_of_week.t 1
perl -I../lib base.secs_since_1970.t 1
perl -I../lib base.split.t 1
perl -I../lib base.week1_day1.t 1
perl -I../lib base.week_of_year.0.t 1
perl -I../lib base.week_of_year.1.t 1
perl -I../lib base.weeks_in_year.t 1
perl -I../lib date.calc.data_date_bsemi.t 1
perl -I../lib date.calc.date_date_approx.t 1
perl -I../lib date.calc.date_date_bapprox.t 1
perl -I../lib date.calc.date_date_business.t 1
perl -I../lib date.calc.date_date_exact.t 1
perl -I../lib date.calc.date_date_semi.t 1
perl -I../lib date.calc.date_delta.romanian.t 1
perl -I../lib date.calc.date_delta_approx.t 1
perl -I../lib date.calc.date_delta_business.0.t 1
perl -I../lib date.calc.date_delta_business.1.t 1
perl -I../lib date.calc.date_delta_business.2.t 1
perl -I../lib date.calc.date_delta_business.3.t 1
perl -I../lib date.calc.date_delta_business.4.t 1
perl -I../lib date.calc.date_delta_business.french.t 1
perl -I../lib date.calc.date_delta_exact.t 1
perl -I../lib date.cmp.t 1
perl -I../lib date.convert.t 1
perl -I../lib date.holiday.0.t 1
perl -I../lib date.holiday.1.t 1
perl -I../lib date.is_business_day.t 1
perl -I../lib date.list_events.0.t 1
perl -I../lib date.list_events.1.t 1
perl -I../lib date.list_holidays.0.t 1
perl -I../lib date.list_holidays.1.t 1
perl -I../lib date.list_holidays.2.t 1
perl -I../lib date.list_holidays.3.t 1
perl -I../lib date.nearest_business_day.t 1
perl -I../lib date.next.t 1
perl -I../lib date.next_business_day.t 1
perl -I../lib date.parse.catalan.t 1
perl -I../lib date.parse.common.t 1
perl -I../lib date.parse.danish.t 1
perl -I../lib date.parse.delta.t 1
perl -I../lib date.parse.dst.t 1
perl -I../lib date.parse.french.t 1
perl -I../lib date.parse.holidays.t 1
perl -I../lib date.parse.iso.t 1
perl -I../lib date.parse.italian.t 1
perl -I../lib date.parse.misc.0.t 1
perl -I../lib date.parse.misc.1.t 1
perl -I../lib date.parse.period.t 1
perl -I../lib date.parse.polish.t 1
perl -I../lib date.parse.portuguese.t 1
perl -I../lib date.parse.romanian.t 1
perl -I../lib date.parse.russian.t 1
perl -I../lib date.parse.spanish.t 1
perl -I../lib date.parse.swedish.t 1
perl -I../lib date.parse_date.common.t 1
perl -I../lib date.parse_date.iso.t 1
perl -I../lib date.parse_date.misc.0.t 1
perl -I../lib date.parse_date.misc.1.t 1
perl -I../lib date.parse_format.t 1
perl -I../lib date.parse_time.t 1
perl -I../lib date.prev.t 1
perl -I../lib date.prev_business_day.t 1
perl -I../lib date.printf.0.t 1
perl -I../lib date.printf.1.t 1
perl -I../lib date.secs_since_1970_GMT.0.t 1
perl -I../lib date.secs_since_1970_GMT.1.t 1
perl -I../lib date.set.0.t 1
perl -I../lib date.set.1.t 1
perl -I../lib date.set.2.t 1
perl -I../lib date.set.3.t 1
perl -I../lib date.week_of_year.0.t 1
perl -I../lib date.week_of_year.1.t 1
perl -I../lib delta.calc.delta_delta_approx.t 1
perl -I../lib delta.calc.delta_delta_business.0.t 1
perl -I../lib delta.calc.delta_delta_business.1.t 1
perl -I../lib delta.calc.delta_delta_exact.t 1
perl -I../lib delta.cmp.t 1
perl -I../lib delta.convert.t 1
perl -I../lib delta.parse.fract.t 1
perl -I../lib delta.parse.t 1
perl -I../lib delta.printf.t 1
perl -I../lib delta.set.t 1
perl -I../lib delta.type.t 1
perl -I../lib delta.value.t 1
perl -I../lib dm5.convtz.t 1
perl -I../lib dm5.date.t 1
perl -I../lib dm5.date_date_0.t 1
perl -I../lib dm5.date_date_1.t 1
perl -I../lib dm5.date_date_2a.t 1
perl -I../lib dm5.date_date_2b.t 1
perl -I../lib dm5.date_delta_0.t 1
perl -I../lib dm5.date_delta_1.t 1
perl -I../lib dm5.date_delta_2a.t 1
perl -I../lib dm5.date_delta_2b.t 1
perl -I../lib dm5.date_delta_french.t 1
perl -I../lib dm5.date_delta_sign.t 1
perl -I../lib dm5.date_french.t 1
perl -I../lib dm5.date_german.t 1
perl -I../lib dm5.date_misc_a.t 1
perl -I../lib dm5.date_misc_b.t 1
perl -I../lib dm5.date_romanian.t 1
perl -I../lib dm5.date_today_0.t 1
perl -I../lib dm5.date_today_1.t 1
perl -I../lib dm5.delta_a.t 1
perl -I../lib dm5.delta_b.t 1
perl -I../lib dm5.delta_delta_0.t 1
perl -I../lib dm5.delta_delta_1.t 1
perl -I../lib dm5.delta_delta_2a.t 1
perl -I../lib dm5.delta_delta_2b.t 1
perl -I../lib dm5.delta_format.t 1
perl -I../lib dm5.delta_romanian.t 1
perl -I../lib dm5.events.t 1
perl -I../lib dm5.getnext.t 1
perl -I../lib dm5.getprev.t 1
perl -I../lib dm5.normalize_business.t 1
perl -I../lib dm5.nthday.t 1
perl -I../lib dm5.recur_0.t 1
perl -I../lib dm5.recur_1.t 1
perl -I../lib dm5.settime.t 1
perl -I../lib dm5.unixdate.t 1
perl -I../lib orig.convtz.t 1
perl -I../lib orig.date_isholiday.t 1
perl -I../lib orig.datecalc.date_date.t 1
perl -I../lib orig.datecalc.date_delta.0.t 1
perl -I../lib orig.datecalc.date_delta.1.t 1
perl -I../lib orig.delta_format.t 1
perl -I../lib orig.eventslist.t 1
perl -I../lib orig.getnext.t 1
perl -I../lib orig.getprev.t 1
perl -I../lib orig.nthdayofyear.t 1
perl -I../lib orig.parsedatedelta.t 1
perl -I../lib orig.parsedatestring.t 1
perl -I../lib orig.parserecur.t 1
perl -I../lib orig.settime.t 1
perl -I../lib orig.unixdate.t 1
perl -I../lib recur.dates.0.t 1
perl -I../lib recur.dates.1.t 1
perl -I../lib recur.dates.2.t 1
perl -I../lib recur.frequency.t 1
perl -I../lib recur.nth.t 1
perl -I../lib tz.all_periods.t 1
perl -I../lib tz.convert.t 1
perl -I../lib tz.convert_from_gmt.t 1
perl -I../lib tz.convert_to_gmt.t 1
perl -I../lib tz.date_period.t 1
perl -I../lib tz.define_abbrev.t 1
perl -I../lib tz.define_alias.t 1
perl -I../lib tz.define_offset.t 1
perl -I../lib tz.periods.t 1
perl -I../lib tz.zone.t 1
perl -I../lib tzdata._ruleinfo.t 1
perl -I../lib tzdata._zoneinfo.t 1
